# Generated by Django 5.0.1 on 2024-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_feature1', models.FloatField()),
                ('continuous_feature2', models.FloatField()),
                ('categorical_feature', models.IntegerField()),
            ],
        ),
    ]
